name: Test
on: [ push, pull_request ]
env:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
jobs:
  unit-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: mvn -B -e -DskipITs install
        shell: bash
  integration-test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Build project with Java 11
        run: mvn -B -e -DskipTests install
        shell: bash
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run integration tests
        run: mvn -B -e -f zeugma-guidance verify
        shell: bash
